### Get Jobs
GET http://localhost:3000/user

### Create Job
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "toyota@gmail.com",
    "password": "toy123"
}

### Put Job
PATCH  http://localhost:3000/user/2
content-type: application/json

{
    "name": "Donald Trump jr.",
    "email": "d.trump@gmail.com"
}

### Delete Job
DELETE http://localhost:3000/user/1
content-type: application/json