### Get Jobs
GET http://localhost:3000/user

### Create Job
POST http://localhost:3003/api/jobs
content-type: application/json

{
    "company": "Temirtau23",
    "geography": "Budju, USA",
    "jobLink": "https://devrelcareers.com/job/8",
    "title": "Full Stack"
}

### Put Job
PATCH  http://localhost:3000/user/44
content-type: application/json

{
    "name": "Anki",
    "email": "anki@gmail.com",
    "token": "2323"
}

### Delete Job
DELETE http://localhost:3003/api/jobs/rec_cgc9e9qtft8hg0jj0lq0
content-type: application/json