### Get Jobs
GET http://localhost:3000/user/1

### Create Job
POST http://localhost:3000/user
content-type: application/json

{
    "name": "Miracle",
    "email": "miracle@gmail.com"
}

### Put Job
PATCH  http://localhost:3000/user/44
content-type: application/json

{
    "name": "Anki",
    "email": "anki@gmail.com",
    "token": "2323"
}

### Delete Job
DELETE http://localhost:3000/user/1
content-type: application/json